Document `for_each` and CEL
abcxyz/abc pull request #167
Opened 2023-08-24 18:14 UTC by drevell

2023-08-24 21:08 UTC, pdewilde requested changes

2023-08-24 21:09 UTC, pdewilde commented on README.md
> +- `string.split(split_char)`: we added a "split" metbod on strings. This has the
```suggestion
- `string.split(split_char)`: we added a "split" method on strings. This has the
```

2023-08-24 21:09 UTC, pdewilde approved these changes

2023-08-24 21:12 UTC, pdewilde commented on README.md
> +      key: 'env'
I feel like `env` may not be the best name for an example variable, as its often used as a variable in similar workflow languages (like gh actions).

2023-08-24 21:15 UTC, drevell commented on README.md
> +      values: 'comma_separated_environments.split(",")'
Thanks for catching that

2023-08-25 00:38 UTC, sethvargo approved these changes

2023-08-25 02:52 UTC, merged