Configure CI to run non-hermetic tests
abcxyz/abc pull request #348
Opened 2024-01-05 23:19 UTC by capri-xiyue

fixed #314 
* Configure CI to run non-hermetic tests

2024-01-05 23:37 UTC, drevell requested changes

2024-01-05 23:37 UTC, drevell commented on .gitignore
This file should probably go in a separate PR

2024-01-05 23:42 UTC, capri-xiyue commented on .gitignore
done

2024-01-06 00:07 UTC, capri-xiyue commented
Looks like https://github.com/abcxyz/pkg/blob/00353d11b4931aca33574bd674d85fafc547972c/.github/workflows/go-test.yml#L61 doesn't work with windows. I will try to see whether I can fix abcxyz/pkg to make it also support windows.

2024-01-06 00:46 UTC, capri-xiyue commented
> Looks like https://github.com/abcxyz/pkg/blob/00353d11b4931aca33574bd674d85fafc547972c/.github/workflows/go-test.yml#L61 doesn't work with windows. I will try to see whether I can fix abcxyz/pkg to make it also support windows.

I made the no-skip as the default behavior now as it probably takes longer time for me to fix https://github.com/abcxyz/pkg/blob/00353d11b4931aca33574bd674d85fafc547972c/.github/workflows/go-test.yml#L61, see https://github.com/abcxyz/pkg/pull/255

2024-01-06 01:13 UTC, drevell commented
> > Looks like https://github.com/abcxyz/pkg/blob/00353d11b4931aca33574bd674d85fafc547972c/.github/workflows/go-test.yml#L61 doesn't work with windows. I will try to see whether I can fix abcxyz/pkg to make it also support windows.
> 
> I made the no-skip as the default behavior now as it probably takes longer time for me to fix https://github.com/abcxyz/pkg/blob/00353d11b4931aca33574bd674d85fafc547972c/.github/workflows/go-test.yml#L61, see [abcxyz/pkg#255](https://github.com/abcxyz/pkg/pull/255)

I'm not sure this is the right thing to do. When a user runs `go test ./...` in the abc repo, I think it's a best practice to avoid depending on any external resources.

How about this alternative: look for the GITHUB_ACTIONS environment variable ([docs](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables)). If that variable is present, then we'll go ahead and run the tests in question.

2024-01-08 17:52 UTC, capri-xiyue commented
> > > Looks like https://github.com/abcxyz/pkg/blob/00353d11b4931aca33574bd674d85fafc547972c/.github/workflows/go-test.yml#L61 doesn't work with windows. I will try to see whether I can fix abcxyz/pkg to make it also support windows.
> > 
> > 
> > I made the no-skip as the default behavior now as it probably takes longer time for me to fix https://github.com/abcxyz/pkg/blob/00353d11b4931aca33574bd674d85fafc547972c/.github/workflows/go-test.yml#L61, see [abcxyz/pkg#255](https://github.com/abcxyz/pkg/pull/255)
> 
> I'm not sure this is the right thing to do. When a user runs `go test ./...` in the abc repo, I think it's a best practice to avoid depending on any external resources.
> 
> How about this alternative: look for the GITHUB_ACTIONS environment variable ([docs](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables)). If that variable is present, then we'll go ahead and run the tests in question.

Do you mean set the env like https://github.com/abcxyz/abc/pull/348/commits/dda5280a11f4076c59b88f817f34e9dcd37cb8d1, it won't work as it is a invalid use for a resuable workflow https://github.com/abcxyz/abc/actions/runs/7427742276/workflow?

2024-01-08 19:39 UTC, drevell commented
> Do you mean set the env like [dda5280](https://github.com/abcxyz/abc/commit/dda5280a11f4076c59b88f817f34e9dcd37cb8d1), it won't work as it is a invalid use for a resuable workflow https://github.com/abcxyz/abc/actions/runs/7427742276/workflow? And the GITHUB_ENV is what abcxyz/pkg is doing. I will try to make abcxyz/pkg works with windows. @drevell

I'm thinking we can leave the .github directory the same, and change https://github.com/abcxyz/abc/blob/5b467fd4e3f8897ac307e8dc41a7a7988cf76cba/templates/common/git/git_test.go#L37 from:

```
if os.Getenv(envName) == "" {
  t.Skipf("skipping test because env var %q isn't set", envName)
}
```

to

```
if os.Getenv("ABC_TEST_NON_HERMETIC) == "" && os.Getenv("GITHUB_ACTIONS") == "" {
  t.Skipf("skipping test because env var %q isn't set", envName)
}
```

I haven't tested, but I think this would work because github actions always set the GITHUB_ACTIONS env variable.

2024-01-08 19:41 UTC, capri-xiyue commented
> > Do you mean set the env like [dda5280](https://github.com/abcxyz/abc/commit/dda5280a11f4076c59b88f817f34e9dcd37cb8d1), it won't work as it is a invalid use for a resuable workflow https://github.com/abcxyz/abc/actions/runs/7427742276/workflow? And the GITHUB_ENV is what abcxyz/pkg is doing. I will try to make abcxyz/pkg works with windows. @drevell
> 
> I'm thinking we can leave the .github directory the same, and change
> 
> https://github.com/abcxyz/abc/blob/5b467fd4e3f8897ac307e8dc41a7a7988cf76cba/templates/common/git/git_test.go#L37
> 
> from:
> ```
> if os.Getenv(envName) == "" {
>   t.Skipf("skipping test because env var %q isn't set", envName)
> }
> ```
> 
> to
> 
> ```
> if os.Getenv("ABC_TEST_NON_HERMETIC) == "" && os.Getenv("GITHUB_ACTIONS") == "" {
>   t.Skipf("skipping test because env var %q isn't set", envName)
> }
> ```
> 
> I haven't tested, but I think this would work because github actions always set the GITHUB_ACTIONS env variable.

I've made abcxyz/pkg work with windows. Current the PR is ready to review now with the original approach we want to go.

2024-01-08 19:44 UTC, drevell commented
> I've made abcxyz/pkg work with windows. Current the PR is ready to review now with the original approach we want to go.

Excellent, thank you.

2024-01-08 19:44 UTC, drevell approved these changes

2024-01-08 19:44 UTC, merged