Expand golden-test docs in README
abcxyz/abc pull request #368
Opened 2024-01-19 19:00 UTC by drevell

There's nothing really new here, I'm just adding more material and clarifying a few things.

2024-01-19 19:46 UTC, bradegler requested changes
Two minor spacing issues, otherwise LGTM.

2024-01-19 19:46 UTC, bradegler commented on README.md
> +params.Each "input" in this file must correspond to a template input defined in
```suggestion
params. Each "input" in this file must correspond to a template input defined in
```

2024-01-19 19:46 UTC, bradegler commented on README.md
> +the template's`spec.yaml`. Each required input in the template's spec.yaml must
```suggestion
the template's `spec.yaml`. Each required input in the template's spec.yaml must
```

2024-01-19 19:51 UTC, drevell commented on README.md
> +params.Each "input" in this file must correspond to a template input defined in
🤦

2024-01-19 19:51 UTC, drevell commented on README.md
> +the template's`spec.yaml`. Each required input in the template's spec.yaml must
🤦

2024-01-19 19:51 UTC, bradegler submitted a review, later dismissed

2024-01-22 22:22 UTC, gjonathanhong approved these changes

2024-01-22 22:23 UTC, merged