Add now (current timestamp) as a template variable
abcxyz/abc pull request #472
Opened 2024-03-06 15:29 UTC by sethvargo

2024-03-06 19:08 UTC, drevell requested changes

2024-03-06 19:08 UTC, drevell commented on templates/common/render/render.go
> +	now := strconv.FormatInt(time.Now().UTC().UnixMilli(), 10)
Should this use the overridden value of _now, if it has been overridden?

2024-03-06 19:08 UTC, drevell commented on templates/common/render/render.go
> +	now := strconv.FormatInt(time.Now().UTC().UnixMilli(), 10)
Should this use rp.Clock instead of calling time.Now()?

2024-03-06 19:08 UTC, drevell commented on templates/common/template_funcs_test.go
> +			time:   "0",
Can we have test for a nonzero time?

2024-03-08 00:20 UTC, drevell commented
@sethvargo I pushed the changes we talked about yesterday:

 - Template functions can now vary depending on api_version
 - api_version v1beta6 has been created with support for formatTime and _now_ms

Also refactored some stuff that got bloated as a result and deserves its own package.

I guess technically I'm the reviewer and you're the author on this branch, so I'll approve this PR once you give me an unofficial thumbs up on my changes.

2024-03-08 00:35 UTC, sethvargo reviewed
LGTM

2024-03-08 17:40 UTC, merged